// A little circles that are controled by user and squares that are randomly generated by computer
//who shall take over the screen
//Objects
SquareAttack Attack1;
SquareAttack Attack2; 
SquareAttack Attack3;

void setup() {
 size(800, 600);
  // setting up the attack waves of the squares 
  Attack1 = new SquareAttack(color(122), 8, 80, color(190,9,97)); 
  Attack2 = new SquareAttack(color(255), 10, 100, color(0));
  Attack3 = new SquareAttack(color(0), 14, 200, color(255));
}

void draw() {
  frameRate(24);
  UserCircle();
  AISquare();  
}


// times the automated AI waves
void AISquare()
{
   Attack1.display();
   
  int timer = second();
   
   if (timer % 10 == 4)
   {
     Attack2.display();
   }
   
   if (timer % 20 == 2)
   {
      Attack3.display();
   }
   
}

// Automation of the SquareAttack Class ( Consider it like bosses)
class SquareAttack { 
  color c;
  int thickness;
  int Sizing;
  color outline;
  

  // The Constructor is defined with parameters.  
  SquareAttack(color tempC, int tempThickness, int tempSizing, color tempOutline) { 
    c = tempC;
    thickness = tempThickness;
    Sizing = tempSizing;
    outline = tempOutline;
  }

  void display() {
    float ranX = (random(-50,700));
    float ranY = (random(-5,750));
    fill(c);
    stroke(outline);
    strokeWeight(thickness);
    rect(50 + ranX, 50+ranY, Sizing +(random(1,5)) ,Sizing +random(1,5));
  }
}

void UserCircle()
{
  if (mousePressed)
  {
    fill(150);
    randomCircle();
  } else
  {
    fill(200, 89, 111);
  }
  stroke(225);
  strokeWeight(6);
  ellipse(300, 300, 80, 80);
}


//adding a random element based on user interactions with an initial circle
//additional circles will be added when the the mouse is pressed as shown in UserCircle()
void randomCircle()
{
 fill(random(97),random(89),79);
  stroke(255);
  strokeWeight(random(4,9));
  ellipse(random(0,720),random(0,520),80,80); 
}

//screen Wipe and then restarts the AI component
void keyPressed()
{
  background(random(255),random(100),random(150));
}

//adding a random element based on user interactions with an initial circle
//additional circles will be added when the the mouse is pressed as shown in UserCircle()